version: "3.9"
name: project-source

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password-keycloak
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-db:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=project_source

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
     - "443:443"
    environment:
      VITE_BACKEND_BASE_URL: http://service:8081
      VITE_KEYCLOAK_URL: https://keycloak:8080
      VITE_KEYCLOAK_REALM: project-source
      VITE_KEYCLOAK_CLIENT_ID: frontend


  # service:
  #   build:
  #     context: ./service
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     CASSANDRA_PORT: 9042
  #     CASSANDRA_HOST: cassandra
  #     CASSANDRA_KEYSPACE: project_source
  #     PORT: 8081
  #     CLIENT_ID: backend
  #     KEYCLOAK_REALM: project_source
  #     KEYCLOAK_PORT: 8080
  #     KEYCLOAK_HOSTNAME: http://keycloak
  #   depends_on:
  #     - cassandra
  #     - postgres
  #     - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_HOSTNAME: localhost
      KC_DB_PASSWORD: password-keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_URL_PORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8443:8443"
    command:
      - start --import-realm
    volumes:
      - ./docker/keycloak/realm-export:/opt/keycloak/data/import
#      - ./docker/keycloak/ssl:/opt/keycloak/conf
    depends_on:
      - postgres


volumes:
  cassandra-db:
  postgres-db:
