version: "3.9"
name: project-source

services:
  postgres:
    container_name: project-source-postgres-keycloak-1
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password-keycloak
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  cassandra:
    container_name: project-source-cassandra-1
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-db:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=project-source


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_HOSTNAME: localhost
      KC_DB_PASSWORD: password-keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_URL: jdbc:postgresql://project-source-postgres-keycloak-1:5432/keycloak
      KC_DB_URL_PORT: 5432
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8080:8080"
    command:
      - start-dev
    volumes:
      - ./docker/scripts:/scripts
    depends_on:
      - postgres

volumes:
  cassandra-db:
  postgres-db:
