spring:
  cassandra:
    port: ${CASSANDRA_PORT:9042}
    contact-points: ${CASSANDRA_HOST:cassandra}
    keyspace-name: ${CASSANDRA_KEYSPACE:project_source}
    schema-action: create_if_not_exists
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOSTNAME:https://localhost}:${KEYCLOAK_PORT:8443}/realms/${KEYCLOAK_REALM:project-source}
          jwk-set-uri: ${KEYCLOAK_HOSTNAME:https://localhost}:${KEYCLOAK_PORT:8443}/realms/${KEYCLOAK_REALM:project-source}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resourceId: ${CLIENT_ID:backend}

server:
  port: ${PORT:8081}


