spring:
  cassandra:
    port: 9042
    contact-points: project-source-cassandra-1
    keyspace-name: projectsource
    schema-action: create_if_not_exists

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOSTNAME:http://localhost}:${KEYCLOAK_PORT:18080}/realms/${KEYCLOAK_REALM:project-source}
          jwk-set-uri: ${KEYCLOAK_HOSTNAME:http://localhost}:${KEYCLOAK_PORT:18080}/realms/${KEYCLOAK_REALM:project-source}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resourceId: ${CLIENT_ID:backend}
