FROM openjdk:17-jdk AS runtime

WORKDIR /app

RUN curl -o /usr/local/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh \
    && chmod +x /usr/local/bin/wait-for-it

COPY build/libs/service-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8081

ENTRYPOINT wait-for-it $CASSANDRA_HOST:$CASSANDRA_PORT -- java -jar app.jar

