FROM gradle:7.6-jdk17-alpine AS build

WORKDIR /app

COPY . .

RUN gradle build

RUN rm build/libs/*-plain.jar

FROM eclipse-temurin:17-jdk-alpine AS runtime

WORKDIR /app

COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]

